# Generated by Django 4.1.5 on 2023-02-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_variation_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
